- name: Run Docker Compose script
  hosts: localhost
  become: yes
  tasks:
    - name: Start Docker Compose services
      shell: docker-compose up
      args:
        chdir: /var/lib/jenkins/workspace/eth-project/
