apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - name: frontend
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: backend
    port: 4000
    targetPort: 4000
    protocol: TCP
  
  type: LoadBalancer
